{{ config(materialized='table') }}

-- Unified atomic event fact. Supports xAPI: actor/verb/object/context/result
-- Transform xAPI statements to fact_learning_event (via staging)
-- Note: lms_events removed - MongoDB doesn't have events collection, using only xAPI statements from LRS
select
  cast(event_id as string) as event_id,
  'xapi' as source_system,
  cast(event_id as string) as source_event_key,
  cast(event_timestamp as timestamp) as event_timestamp_utc,
  cast(extract(epoch from date(event_timestamp))::int / 86400 as int) as date_id,
  cast((extract(hour from event_timestamp) * 3600 + extract(minute from event_timestamp) * 60 + extract(second from event_timestamp)) as int) as time_of_day_id,
  cast(timezone as string) as timezone,
  cast(eventType as string) as event_type_key,
  cast(verbId as int) as verb_id,
  cast(verbIri as string) as verb_raw,
  cast(userId as string) as person_id,
  cast(actorType as string) as actor_type,
  cast(impersonatedUserId as string) as impersonated_person_id,
  cast(sessionId as string) as session_id,
  cast(platformId as string) as platform_id,
  cast(ltiToolId as string) as lti_tool_id,
  cast(aiToolId as string) as ai_tool_id,
  cast(deviceId as string) as device_id,
  cast(schoolId as string) as organization_id,
  cast(termId as string) as term_id,
  cast(courseId as string) as course_id,
  cast(sectionId as string) as section_id,
  cast(membershipId as string) as membership_id,
  cast(objectType as string) as object_type_key,
  cast(objectId as string) as object_id,
  cast(targetType as string) as target_type_key,
  cast(targetId as string) as target_id,
  cast(generatedType as string) as generated_type_key,
  cast(generatedId as string) as generated_id,
  cast(contentId as string) as content_id,
  cast(assessmentId as string) as assessment_id,
  cast(itemId as string) as item_id,
  cast(skillId as string) as skill_id,
  cast(standardId as string) as standard_id,
  cast(attemptNumber as int) as attempt_number,
  cast(success as boolean) as success,
  cast(completion as boolean) as completion,
  cast(isCorrect as boolean) as is_correct,
  cast(scoreRaw as float) as score_raw,
  cast(scoreMin as float) as score_min,
  cast(scoreMax as float) as score_max,
  cast(scoreScaled as float) as score_scaled,
  cast(scorePercent as float) as score_percent,
  cast(response as string) as response,
  cast(durationSeconds as int) as duration_seconds,
  cast(latencyMs as int) as latency_ms,
  cast(eventSource as string) as event_source,
  cast(metadata as string) as metadata
from {{ ref('stg_lrs_events') }}
