{{ config(
    materialized='view',
    alias='stg_lrs_events'
) }}

-- Staging model to prepare xAPI statements for silver layer
-- Maps xAPI statement fields to a common event structure
-- Uses JSON extraction functions to read from JSON columns
select
  cast(id as string) as event_id,
  cast(timestamp as timestamp) as event_timestamp,
  -- Extract from JSON columns using JSON_VALUE
  cast(JSON_VALUE(actor, '$.account.name') as string) as userId,
  cast(JSON_VALUE(verb, '$.id') as string) as verbId,
  cast(JSON_VALUE(verb, '$.id') as string) as verbIri,
  cast(null as string) as verbShortCode,
  cast(JSON_VALUE(verb, '$.display.en-US') as string) as verbDescription,
  cast(JSON_VALUE(object, '$.id') as string) as objectId,
  cast(JSON_VALUE(object, '$.objectType') as string) as objectType,
  cast(null as string) as sessionId,
  cast(null as string) as schoolId,
  cast(JSON_VALUE(context, '$.extensions."https://amit.lemida.org/xapi/extensions/course_id"') as string) as courseId,
  cast(null as string) as sectionId,
  cast(null as string) as assessmentId,
  cast(null as string) as skillId,
  cast(null as string) as platformId,
  cast(null as string) as ltiToolId,
  cast(null as string) as aiToolId,
  cast(null as string) as deviceId,
  cast(null as string) as deviceType,
  cast(null as string) as os,
  cast(null as string) as browser,
  cast(null as string) as userAgent,
  cast(null as string) as termId,
  cast(null as string) as membershipId,
  cast(null as string) as targetType,
  cast(null as string) as targetId,
  cast(null as string) as generatedType,
  cast(null as string) as generatedId,
  cast(JSON_VALUE(object, '$.id') as string) as contentId,
  cast(null as string) as itemId,
  cast(null as string) as standardId,
  cast(CAST(JSON_VALUE(context, '$.extensions."https://amit.lemida.org/xapi/extensions/attempts"') AS INT64) as int) as attemptNumber,
  cast(CAST(JSON_VALUE(result, '$.success') AS BOOL) as boolean) as success,
  cast(CAST(JSON_VALUE(result, '$.completion') AS BOOL) as boolean) as completion,
  cast(CAST(JSON_VALUE(result, '$.success') AS BOOL) as boolean) as isCorrect,
  cast(CAST(JSON_VALUE(result, '$.score.raw') AS FLOAT64) as FLOAT64) as scoreRaw,
  cast(CAST(JSON_VALUE(result, '$.score.min') AS FLOAT64) as FLOAT64) as scoreMin,
  cast(CAST(JSON_VALUE(result, '$.score.max') AS FLOAT64) as FLOAT64) as scoreMax,
  cast(CAST(JSON_VALUE(result, '$.score.scaled') AS FLOAT64) as FLOAT64) as scoreScaled,
  cast(null as FLOAT64) as scorePercent,
  cast(JSON_VALUE(result, '$.response') as string) as response,
  cast(CAST(JSON_VALUE(context, '$.extensions."https://amit.lemida.org/xapi/extensions/time_taken_ms"') AS INT64) / 1000 as int) as durationSeconds,
  cast(null as int) as latencyMs,
  cast(JSON_VALUE(verb, '$.id') as string) as eventType,
  cast(null as string) as eventSource,
  cast(null as string) as timezone,
  cast('learner' as string) as actorType,
  cast(null as string) as impersonatedUserId,
  cast(null as string) as toolName,
  cast(null as string) as provider,
  cast(null as string) as modelName,
  cast(null as string) as capabilityType,
  cast(null as string) as platformName,
  cast(null as string) as vendor,
  cast(null as string) as version,
  cast(null as string) as environment,
  cast(null as string) as launchType,
  cast(null as string) as ltiLaunchId,
  cast(null as string) as variantId,
  cast(null as string) as experimentId,
  cast(null as string) as signalType,
  cast(null as string) as signalValue,
  -- Keep full JSON columns for downstream use
  cast(context as string) as metadata,
  cast(TO_JSON_STRING(STRUCT(
    id,
    timestamp,
    actor,
    verb,
    object,
    result,
    context
  )) as string) as fullStatement
from {{ source('raw_lrs', 'lrs_statements') }}

